#Spring 전역 환경 설정
spring:
  profiles:
    active: local
#Batch 명이 없을 경우 배치명 지정
  batch:
    job:
      names: ${job.name:batchStudy}

---
#local 환경 설정
spring:
  config:
    activate:
      on-profile: local
#MySql 데이터베이스 연결
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #Spring batch가 사용하는 Schema생성 방식 설정
  #never:미생성, always:매번생성, embedded:테스트용 메모리 DB용
  batch:
    jdbc:
      initialize-schema: never